import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "gu" | "te";

export const translations = {
  en: {
    // Navbar
    manifesto: "Manifesto",
    services: "Services",
    cases: "Cases",
    about: "About",
    resources: "Resources",
    blog: "Blog",
    growth_assets: "Growth Assets",
    talk_to_us: "Talk to us",
    jupiter_title: "Jupiter Engineering Solutions",
    home: "Home",
    order: "Connect with us",
    products: "Products",
    about_us: "About Us",
    others: "Others",
    sustainability: "Sustainability",
    about_hero_title_main: "Jupiter Engineering ",
    about_hero_title_italic: "Solutions",
    about_hero_sub: "Established in 2018, we are a leading force in the fabrication, engineering and manufacturing of process equipment. With over three decades of collective experience, our team delivers cutting-edge thermal solutions for pharmaceuticals, chemicals, refineries, petrochemicals and oil & gas industries.",
    about_vision_title: "Our Vision & Values",
    about_vision_desc: "We are committed to becoming the future leader in all things graphite. Precision, integrity, and innovation form the cornerstones of our engineering philosophy. We rely on expertise to optimize your processes for the best possible outcomes.",
    about_standards_title: "Compliance & Design Standards",
    about_standards_desc: "We adhere strictly to international codes including ASME, TEMA, and DIN standards. Our advanced design capabilities include HTRI 9, proprietary calculation software, AspenTech process simulation, AutoCAD and SolidWorks for maximum design accuracy.",
    // About page extra keys
    about_value_1: "Thermal Precision Engineering",
    about_value_2: "Material Durability & Graphite Mastery",
    about_value_3: "Customer Lifecycle Partnership",
    about_cta_title: "Looking for a custom build?",
    about_cta_desc: "Consult with our thermal engineering specialists to run a certified HTRI heat transfer calculation for your parameters.",
    about_cta_btn: "Schedule a Consultation",
    order_hero_title_main: "Connect with ",
    order_hero_title_italic: "us",
    order_hero_sub: "Get in touch with our engineering team to discuss your process requirements, design custom heat exchangers, or request standard technical evaluations.",
    order_form_params: "Process Parameters",
    order_form_hot_in: "Hot Side Inlet Temp (°C)",
    order_form_hot_out: "Hot Side Outlet Temp (°C)",
    order_form_cold_in: "Cold Side Inlet Temp (°C)",
    order_form_cold_out: "Cold Side Outlet Temp (°C)",
    order_form_flow: "Flow Rate (kg/h)",
    order_form_name: "Full Name",
    order_form_email: "Email Address",
    order_form_message: "Project Requirements / Message",
    order_form_material: "Material Selection",
    order_form_type: "Exchanger Type",
    order_form_submit: "Send Request",
    order_form_success: "Thank you! Our engineering team will get back to you soon.",
    
    // Hero
    hero_headline_1: "The Future Leader",
    hero_headline_2: "In All Things",
    hero_headline_3: "Graphite",
    hero_subtext: "Fabrication, engineering, and manufacturing of process equipment for critical industrial applications. With over three decades of collective experience, we rely on expertise to optimize your processes for the best possible outcomes.",
    hero_cta: "Request a Technical Consultation",
    
    // PainPoints
    painpoints_title: "Your processes are world-class. Your thermal equipment shouldn't hold you back.",
    problem_1_title: "Corrosion & Equipment Failure",
    problem_1_body: "Standard metal heat exchangers degrade rapidly when handling aggressive chemicals like HCl, H₂SO₄ and phosphoric acid, causing hazardous leaks and expensive plant shutdowns.",
    problem_2_title: "Suboptimal Thermal Design & Fouling",
    problem_2_body: "Generic off-the-shelf equipment lacks precise HTRI thermal ratings, resulting in high pressure drops, energy wastage, and frequent tube fouling that reduces heat transfer efficiency.",
    problem_3_title: "Quality Inspection & Safety Compliance Gaps",
    problem_3_body: "Substandard welding and lack of rigorous non-destructive testing (Ultrasonic, Radiography, Dye Penetration, Helium) lead to failure risks in critical process zones.",
    problem_4_title: "Inadequate Production Capacity & Long Lead Times",
    problem_4_body: "Manufacturers without state-of-the-art machinery, 35-foot EOT cranes, and 6,000 sq. ft. workshops cannot handle large structural skids or ensure timely turnaround for critical projects.",
    problem_5_title: "Lack of Reliable Maintenance & Re-tubing",
    problem_5_body: "Once installed, finding prompt on-site cleaning, heat exchanger repairing, and part replacement services is difficult, leading to extended operational downtime and production losses.",
    painpoints_cta_title: "Ready to optimize your heat transfer processes? Let's discuss your requirements.",
    painpoints_cta_btn: "Request a Technical Consultation",
    
    // Cases
    cases_title_1: "Proven with 30+",
    cases_title_2: "industrial plants that trusted us",
    cases_title_3: "in optimizing their heat transfer",
    cases_explore_btn: "Explore our cases",
    cases_explore_hover: "Explore case",
    cases_coming_soon: "Coming Soon",
    
    // Services (Heat Exchangers)
    services_1_heading: "Shell & Tube Exchangers",
    services_1_body: "Engineered for high-pressure and high-temperature processes. We design shell and tube heat exchangers that deliver optimal thermal performance and maximum durability under extreme industrial conditions across pharma, chemical, and petrochemical plants.",
    services_2_heading: "Graphite Technology",
    services_2_body: "Unmatched corrosion resistance for aggressive chemical processing. Our graphite polyblock heat exchangers provide exceptional thermal conductivity, making them ideal for handling highly corrosive acids like HCl, H₂SO₄, and phosphoric acid.",
    services_3_heading: "Precision Thermal Design",
    services_3_body: "Optimized heat transfer using advanced HTRI 9 calculations, proprietary software, and AspenTech process simulations. We customize tube configurations and baffle spacing to minimize pressure drop and prevent fouling.",
    services_4_heading: "Lifecycle Performance",
    services_4_body: "Complete maintenance, refurbishing, and re-tubing services backed by our 6,000 sq. ft. workshop with 35-foot EOT crane. We ensure your heat transfer systems run continuously at peak performance.",
    services_discover_btn: "Discover our solutions",
    
    // Testimonials
    testimonials_title_1: "We engineer thermal &",
    testimonials_title_2: "process systems to last",
    testimonials_subtext: "From thermal design to custom fabrication, we deliver heat exchangers and pressure vessels engineered for maximum operational reliability across pharmaceuticals, chemicals, and refineries.",
    
    // CTA Section
    cta_title_1: "Choose engineered reliability",
    cta_title_2: "over catalog equipment",
    cta_subtext: "Generic process equipment compromises thermal efficiency and chemical safety. Optimize your system using custom-engineered solutions designed with HTRI precision and built to last.",
    cta_table_isolated_title: "Catalog Equipment",
    cta_table_isolated_sub: "Standard configurations & off-the-shelf process vessels",
    cta_table_wgb_title: "Jupiter Engineered Systems",
    cta_table_wgb_sub: "Custom-engineered process equipment for maximum reliability",
    cta_row_1_bad: "Standard metal exchangers corrode rapidly under harsh chemicals, leading to hazardous leaks and shutdowns.",
    cta_row_1_good: "Custom graphite polyblocks and premium alloys ensure unmatched corrosion resistance for aggressive acid environments.",
    cta_row_2_bad: "Standard configurations suffer from high pressure drops and low thermal efficiency due to generic tube layouts.",
    cta_row_2_good: "HTRI 9, proprietary software, and AspenTech simulations maximize heat transfer with precisely optimized designs.",
    cta_row_3_bad: "Minimal post-fabrication testing leads to high risk of leakage and failure in critical production processes.",
    cta_row_3_good: "Compulsory Helium, Radiography, Ultrasonic, and Hydrostatic testing verify zero defects before delivery.",
    cta_row_4_bad: "Inflexible designs that are difficult to fit within pre-existing plant layouts and piping configurations.",
    cta_row_4_good: "Tailor-made structural skids and customized piping layouts fit your exact space and process requirements.",
    cta_btn: "Talk to an engineer",
    
    // Footer
    footer_headline_1: "Talk to an engineer,",
    footer_headline_2: "not sales",
    footer_follow: "Follow us",
    footer_rights: "© 2026 Jupiter Engineering Solutions. All rights reserved.",
    footer_privacy: "Privacy Policy",
    footer_imprint: "Imprint",
    footer_cookies: "Cookies",
    footer_branding: "Branding by Ali",
    footer_design: "Design by Dylan",
    footer_tagline: "Efficiency Through Innovation: Your Heat, Our Exchange",
    footer_address: "Gat No. 20/5, Besides Caves County Resorts, Mumbai Agra Highway, Villholi, Nashik - 422010",
    footer_email: "jupiterengg18@gmail.com",
    footer_phone: "8600031275 / 9766963331",

    // Sustainability Page
    sust_commitment: "Our Commitment",
    sust_hero_title_1: "Engineering a",
    sust_hero_title_italic: "greener",
    sust_hero_title_2: "industrial future",
    sust_hero_desc: "At Jupiter Engineering Solutions, sustainability isn't a checkbox — it's embedded in every heat exchanger we design, every material we source, and every process we optimise. We believe high-performance thermal engineering and environmental responsibility are inseparable.",
    sust_hero_btn: "View Environment Policy",
    sust_green_scheme_title: "Our Green Scheme",
    sust_green_scheme_desc: "Jupiter Engineering doesn't just manufacture world-class heat transfer equipment — we do it with deep respect for the environment at every stage: from raw material sourcing and production to installation, operation, and end-of-life recycling. Sustainability is built into our DNA.",
    sust_green_init_title: "Fostering",
    sust_green_init_italic: "Green",
    sust_green_init_title_2: "Initiatives",
    sust_green_init_desc: "Three pillars that drive our environmental strategy across every facility.",
    sust_card_1_title: "Thermal Waste Recovery",
    sust_card_1_desc: "Our heat exchangers are engineered to recapture up to 92% of process waste heat, redirecting it back into production cycles — dramatically cutting primary fuel consumption and CO₂ output.",
    sust_card_2_title: "Low-Emission Materials",
    sust_card_2_desc: "We exclusively use synthetic graphite and corrosion-resistant alloys that are 100% recyclable. Our manufacturing processes eliminate volatile organic compound (VOC) release at the source.",
    sust_card_3_title: "Water-Positive Operations",
    sust_card_3_desc: "Zero-discharge water treatment plants across all facilities ensure that every drop of process water is treated, recycled, and returned — achieving water-positive status since 2024.",
    sust_learn_more: "Learn more",
    sust_env_title_1: "Environment",
    sust_env_title_italic: "Protection",
    sust_env_title_2: "Initiatives",
    sust_env_1: "Closed-loop coolant systems preventing groundwater contamination",
    sust_env_2: "Monthly stack emission testing exceeding CPCB norms by 40%",
    sust_env_3: "ISO 14001:2015 certified environmental management across all plants",
    sust_env_4: "Installation of electrostatic precipitators and bag filters at all dust points",
    sust_env_5: "Bimonthly ambient air quality monitoring by NABL-accredited agencies",
    sust_env_6: "Solid waste segregation with 95% recycling rate — zero landfill target by 2027",
    sust_env_7: "Rainwater harvesting infrastructure capturing 12 million litres annually",
    sust_env_8: "Replacement of furnace oil with natural gas across all thermal processes",
    sust_env_9: "Green belt development with 15,000+ native trees planted across facilities",
    sust_safety_label: "Safety First",
    sust_safety_title_1: "Where precision meets",
    sust_safety_title_italic: "protection",
    sust_safety_1: "All personnel equipped with PPE — helmets, heat-resistant gloves, safety shoes, and eye protection",
    sust_safety_2: "Monthly safety drills and quarterly emergency evacuation simulations",
    sust_safety_3: "CCTV-monitored confined space entry with gas detection protocols",
    sust_safety_4: "Fire extinguishers and hydrant systems inspected weekly by certified engineers",
    sust_safety_5: "Pressure vessels and storage tanks undergo annual load-bearing certification",
    sust_safety_btn: "View Safety Policy",
    sust_health_label: "Health",
    sust_health_title_1: "We Care For Our",
    sust_health_title_italic: "People",
    sust_health_desc: "Our plants have adopted wide-ranging initiatives to protect the health and wellbeing of every employee. Here are some of the key measures adopted across our facilities.",
    sust_health_1: "ESIC & Personal Accident coverage for all workers",
    sust_health_2: "Biannual health screenings by qualified physicians",
    sust_health_3: "Mediclaim & PA Policy for officers and staff",
    sust_health_4: "Dust, fumes & heat exposure controlled below permissible limits",
    sust_cta_title: "Partner with us for a sustainable future",
    sust_cta_desc: "Explore how our thermally efficient, low-emission heat exchangers can reduce your plant's carbon footprint while improving process performance.",
    sust_cta_btn: "Schedule a Consultation",

    // Testimonials content
    test_1_text: "We commissioned Jupiter for a custom set of shell & tube heat exchangers. The thermal efficiency exceeded our specifications by 12%, significantly reducing our utility costs.",
    test_2_name: "Dr. Rajesh Mehta",
    test_2_title: "Director of Operations, Chemie India",
    test_2_text: "Jupiter's design engineering team has deep technical expertise. They ran comprehensive HTRI simulations to optimize baffle spacing, resolving a chronic fouling issue that had plagued our plant for years.",
    test_3_name: "Vikram Malhotra",
    test_3_title: "VP Projects, Petrochem Refinery",
    test_3_text: "For our refinery expansion, we needed ASME-certified pressure vessels on a strict timeline. Jupiter delivered ahead of schedule, with flawless weld quality and complete documentation.",
    test_4_text: "Their graphite heat exchangers solved our aggressive acid heating issues. Truly excellent corrosion resistance and prompt service.",
    test_5_name: "Amitabh Shah",
    test_5_title: "Chief Engineer, Gujarat Chlor-Alkali",
    test_5_text: "The team doesn't just fabricate; they provide valuable design feedback. Their recommendations on tube sheet materials saved us from premature galvanic corrosion.",
    test_6_name: "Sanjay Reddy",
    test_6_title: "General Manager, Deccan Power Corp",
    test_6_text: "Jupiter helped us refurbish our large steam condensers during a short maintenance shutdown. Their 24/7 support and precision re-tubing got us back online on time.",
  },
  gu: {
    // Navbar
    manifesto: "મેનિફેસ્ટો",
    services: "સેવાઓ",
    cases: "કેસો",
    about: "અમારા વિશે",
    resources: "સંસાધનો",
    blog: "બ્લોગ",
    growth_assets: "ગ્રોથ એસેટ્સ",
    talk_to_us: "અમારો સંપર્ક કરો",
    jupiter_title: "જ્યુપિટર એન્જિનિયરિંગ સોલ્યુશન્સ",
    home: "હોમ",
    order: "અમારી સાથે જોડાઓ",
    products: "પ્રોડક્ટ્સ",
    about_us: "અમારા વિશે",
    others: "અન્ય",
    sustainability: "સાતત્યતા",
    about_hero_title_main: "જ્યુપિટર એન્જિનિયરિંગ ",
    about_hero_title_italic: "સોલ્યુશન્સ",
    about_hero_sub: "2018 માં સ્થાપિત, અમે પ્રોસેસ ઇક્વિપમેન્ટના ફેબ્રિકેશન, એન્જિનિયરિંગ અને મેન્યુફેક્ચરિંગમાં અગ્રણી બળ છીએ. ત્રણ દાયકાથી વધુના સંયુક્ત અનુભવ સાથે, અમારી ટીમ ફાર્માસ્યુટિકલ્સ, કેમિકલ્સ, રિફાઇનરી, પેટ્રોકેમિકલ્સ અને ઓઇલ & ગેસ ઉદ્યોગો માટે અત્યાધુનિક થર્મલ સોલ્યુશન્સ પ્રદાન કરે છે.",
    about_vision_title: "અમારું વિઝન અને મૂલ્યો",
    about_vision_desc: "અમે ગ્રેફાઇટ ક્ષેત્રમાં ભવિષ્યના લીડર બનવા માટે પ્રતિબદ્ધ છીએ. ચોકસાઈ, અખંડિતતા અને નવીનતા એ અમારી એન્જિનિયરિંગ ફિલોસોફીના પાયાના પથ્થરો છે. શ્રેષ્ઠ પરિણામો માટે અમે નિપુણતા પર આધાર રાખીએ છીએ.",
    about_standards_title: "પાલન અને ડિઝાઇન ધોરણો",
    about_standards_desc: "અમે ASME, TEMA અને DIN ધોરણો સહિત આંતરરાષ્ટ્રીય નિયમોનું ચુસ્તપણે પાલન કરીએ છીએ. અમારી અદ્યતન ડિઝાઇન ક્ષમતાઓમાં HTRI 9, પ્રોપ્રાયટરી સોફ્ટવેર, AspenTech પ્રોસેસ સિમ્યુલેશન, AutoCAD અને SolidWorks નો સમાવેશ થાય છે.",
    about_value_1: "થર્મલ પ્રિસિઝન એન્જિનિયરિંગ",
    about_value_2: "મટિરિયલ ટકાઉપણું અને ગ્રેફાઇટ નિપુણતા",
    about_value_3: "ગ્રાહક જીવનચક્ર ભાગીદારી",
    about_cta_title: "કસ્ટમ બિલ્ડ શોધી રહ્યા છો?",
    about_cta_desc: "તમારા પેરામીટર્સ માટે પ્રમાણિત HTRI હીટ ટ્રાન્સફર ગણતરી ચલાવવા માટે અમારા થર્મલ એન્જિનિયરિંગ નિષ્ણાતો સાથે પરામર્શ કરો.",
    about_cta_btn: "પરામર્શ શેડ્યૂલ કરો",
    order_hero_title_main: "અમારી સાથે ",
    order_hero_title_italic: "જોડાઓ",
    order_hero_sub: "તમારી પ્રક્રિયા જરૂરિયાતો, કસ્ટમ હીટ એક્સચેન્જર્સની ડિઝાઇન અથવા તકનીકી મૂલ્યાંકન માટે અમારી એન્જિનિયરિંગ ટીમ સાથે સંપર્ક કરો.",
    order_form_params: "પ્રક્રિયા પેરામીટર્સ",
    order_form_hot_in: "હોટ સાઇડ ઇનલેટ ટેમ્પ (°C)",
    order_form_hot_out: "હોટ સાઇડ આઉટલેટ ટેમ્પ (°C)",
    order_form_cold_in: "કોલ્ડ સાઇડ ઇનલેટ ટેમ્પ (°C)",
    order_form_cold_out: "કોલ્ડ સાઇડ આઉટલેટ ટેમ્પ (°C)",
    order_form_flow: "ફ્લો રેટ (kg/h)",
    order_form_name: "પૂરું નામ",
    order_form_email: "ઇમેઇલ સરનામું",
    order_form_message: "પ્રોજેક્ટ જરૂરિયાતો / સંદેશ",
    order_form_material: "મટિરિયલ પસંદગી",
    order_form_type: "એક્સચેન્જર પ્રકાર",
    order_form_submit: "વિનંતી મોકલો",
    order_form_success: "આભાર! અમારી એન્જિનિયરિંગ ટીમ ટૂંક સમયમાં તમારો સંપર્ક કરશે.",
    // PainPoints
    painpoints_title: "તમારી પ્રક્રિયાઓ વર્લ્ડ-ક્લાસ છે. તમારા થર્મલ સાધનો તેમાં અવરોધ ન બનવા જોઈએ.",
    problem_1_title: "કાટ અને સાધનોની નિષ્ફળતા",
    problem_1_body: "જ્યારે આક્રમક રસાયણો જેમ કે HCl, H₂SO₄ અને ફોસ્ફોરિક એસિડ સાથે કામ કરવામાં આવે છે, ત્યારે સામાન્ય મેટલ હીટ એક્સચેન્જર્સ ઝડપથી બગડે છે, જેના કારણે જોખમી લીકેજ અને મોંઘા પ્લાન્ટ બંધ થાય છે.",
    problem_2_title: "બિન-ઓપ્ટિમલ થર્મલ ડિઝાઇન અને ચોકિંગ",
    problem_2_body: "સામાન્ય સાધનોમાં HTRI થર્મલ રેટિંગ્સનો અભાવ હોય છે, જેના પરિણામે ઊંચો પ્રેશર ડ્રોપ, ઉર્જાનો બગાડ અને ટ્યુબમાં વારંવાર જમા થતો કચરો હીટ ટ્રાન્સફર કાર્યક્ષમતા ઘટાડે છે.",
    problem_3_title: "ગુણવત્તા અને સલામતી પાલનમાં ખામીઓ",
    problem_3_body: "નબળા વેલ્ડિંગ અને કઠોર નોન-ડિસ્ટ્રક્ટિવ ટેસ્ટિંગ (અલ્ટ્રાસોનિક, રેડિયોગ્રાફી, ડાય પેનિટ્રેશન, હિલિયમ) ના અભાવે જોખમી પ્રક્રિયા વિસ્તારોમાં નિષ્ફળતાનું જોખમ વધે છે.",
    problem_4_title: "અપૂરતી ઉત્પાદન ક્ષમતા અને વિલંબ",
    problem_4_body: "આધુનિક મશીનરી, 35 ફૂટ EOT ક્રેન અને 6,000 ચો.ફૂટ. વર્કશોપ વિનાના ઉત્પાદકો મોટા સ્ટ્રક્ચરલ સ્કીડને હેન્ડલ કરી શકતા નથી અથવા સમયસર કામ પૂર્ણ કરી શકતા નથી.",
    problem_5_title: "લાંબા ગાળાની જાળવણી અને સેવાઓનો અભાવ",
    problem_5_body: "ઇન્સ્ટોલેશન પછી, સમયસર ઓન-સાઇટ ક્લિનિંગ, હીટ એક્સચેન્જર રિપેરિંગ અને પાર્ટ્સ રિપ્લેસમેન્ટ મેળવવું મુશ્કેલ બને છે, જેથી પ્લાન્ટ લાંબો સમય બંધ રહે છે.",
    painpoints_cta_title: "તમારી હીટ ટ્રાન્સફર પ્રક્રિયાઓને ઓપ્ટિમાઇઝ કરવા માટે તૈયાર છો? ચાલો ચર્ચા કરીએ.",
    painpoints_cta_btn: "ટેકનિકલ પરામર્શ માટે વિનંતી કરો",
    
    // Cases
    cases_title_1: "30+ ઔદ્યોગિક પ્લાન્ટ્સ સાથે સાબિત,",
    cases_title_2: "જેમણે તેમના હીટ ટ્રાન્સફરને ઓપ્ટિમાઇઝ કરવા માટે",
    cases_title_3: "અમારા પર વિશ્વાસ મૂક્યો છે",
    cases_explore_btn: "અમારા કેસો જુઓ",
    cases_explore_hover: "કેસ જુઓ",
    cases_coming_soon: "ટૂંક સમયમાં આવી રહ્યું છે",
    
    // Services (Heat Exchangers)
    services_1_heading: "શેલ અને ટ્યુબ એક્સચેન્જર્સ",
    services_1_body: "ઉચ્ચ દબાણ અને ઉચ્ચ તાપમાનની પ્રક્રિયાઓ માટે એન્જિનિયર્ડ. અમે ફાર્મા, કેમિકલ અને પેટ્રોકેમિકલ પ્લાન્ટ્સમાં કઠિન ઔદ્યોગિક પરિસ્થિતિઓમાં શ્રેષ્ઠ થર્મલ પ્રદર્શન અને મહત્તમ ટકાઉપણું પ્રદાન કરતા શેલ અને ટ્યુબ એક્સચેન્જર્સ ડિઝાઇન કરીએ છીએ.",
    services_2_heading: "ગ્રેફાઇટ ટેકનોલોજી",
    services_2_body: "આક્રમક રાસાયણિક પ્રક્રિયાઓ માટે અતુલ્ય કાટ પ્રતિકારક શક્તિ. અમારા ગ્રેફાઇટ પોલીબ્લોક હીટ એક્સચેન્જર્સ અસાધારણ થર્મલ વાહકતા પ્રદાન કરે છે, જે HCl, H₂SO₄ અને ફોસ્ફોરિક એસિડ જેવા અતિશય કાટ ખાનારા દ્રાવણોના સંચાલન માટે આદર્શ બનાવે છે.",
    services_3_heading: "ચોક્કસ થર્મલ ડિઝાઇન",
    services_3_body: "અદ્યતન HTRI 9 ગણતરીઓ, પ્રોપ્રાયટરી સોફ્ટવેર અને AspenTech પ્રોસેસ સિમ્યુલેશનનો ઉપયોગ કરીને ઓપ્ટિમાઇઝ હીટ ટ્રાન્સફર. પ્રેશર ડ્રોપ ઘટાડવા અને ટ્યુબમાં જમા થતા કચરાને રોકવા માટે અમે ટ્યુબ ગોઠવણી અને બેફલ સ્પેસિંગને કસ્ટમાઇઝ કરીએ છીએ.",
    services_4_heading: "લાઇફસાયકલ પર્ફોર્મન્સ",
    services_4_body: "સંપૂર્ણ જાળવણી, નવીનીકરણ અને રી-ટ્યુબિંગ સેવાઓ, 35 ફૂટ EOT ક્રેન સાથે અમારા 6,000 ચો.ફૂટ. વર્કશોપ દ્વારા સમર્થિત. અમે ખાતરી કરીએ છીએ કે તમારી હીટ ટ્રાન્સફર સિસ્ટમ્સ પીક પર્ફોર્મન્સ પર સતત કાર્યરત રહે.",
    services_discover_btn: "અમારા સોલ્યુશન્સ શોધો",
    
    // Testimonials
    testimonials_title_1: "અમે થર્મલ અને પ્રોસેસ",
    testimonials_title_2: "સિસ્ટમ્સને ટકાઉ બનાવીએ છીએ",
    testimonials_subtext: "થર્મલ ડિઝાઇનથી લઈને કસ્ટમ ફેબ્રિકેશન સુધી, અમે ફાર્માસ્યુટિકલ્સ, કેમિકલ્સ અને રિફાઇનરીઓમાં મહત્તમ ઓપરેશનલ વિશ્વસનીયતા માટે એન્જિનિયર્ડ હીટ એક્સચેન્જર્સ અને પ્રેશર વેસલ્સ પ્રદાન કરીએ છીએ.",
    
    // CTA Section
    cta_title_1: "કેટલોગ સાધનોના બદલે",
    cta_title_2: "એન્જિનિયર્ડ વિશ્વસનીયતા પસંદ કરો",
    cta_subtext: "સામાન્ય પ્રક્રિયા સાધનો થર્મલ કાર્યક્ષમતા અને રાસાયણિક સલામતી સાથે સમાધાન કરે છે. HTRI ચોક્કસાઈ સાથે ડિઝાઇન કરેલા અને ટકાઉ બનાવેલા કસ્ટમ-એન્જિનિયર્ડ થર્મલ ઉકેલો સાથે તમારી સિસ્ટમને ઓપ્ટિમાઇઝ કરો.",
    cta_table_isolated_title: "કેટલોગ સાધનો",
    cta_table_isolated_sub: "પ્રમાણભૂત ડિઝાઇન અને સામાન્ય પ્રોસેસ વેસલ્સ",
    cta_table_wgb_title: "જ્યુપિટર એન્જિનિયર્ડ સિસ્ટમ્સ",
    cta_table_wgb_sub: "મહત્તમ વિશ્વસનીયતા માટે કસ્ટમ-ડિઝાઇન કરેલા પ્રક્રિયા સાધનો",
    cta_row_1_bad: "સામાન્ય મેટલ એક્સચેન્જર્સ આક્રમક રસાયણો હેઠળ ઝડપથી કાટ ખાય છે, જેના કારણે જોખમી લીકેજ અને પ્લાન્ટ બંધ થાય છે.",
    cta_row_1_good: "કસ્ટમ ગ્રેફાઇટ પોલીબ્લોક્સ અને પ્રીમિયમ એલોય આક્રમક એસિડ વાતાવરણ માટે અજોડ કાટ પ્રતિકાર સુનિશ્ચિત કરે છે.",
    cta_row_2_bad: "પ્રમાણભૂત રૂપરેખાંકનો સામાન્ય ટ્યુબ લેઆઉટને કારણે ઊંચા પ્રેશર ડ્રોપ અને ઓછી થર્મલ કાર્યક્ષમતાથી પીડાય છે.",
    cta_row_2_good: "HTRI 9, પ્રોપ્રાયટરી સોફ્ટવેર અને AspenTech સિમ્યુલેશન ચોક્કસ ઓપ્ટિમાઇઝ ડિઝાઇન સાથે હીટ ટ્રાન્સફરને મહત્તમ કરે છે.",
    cta_row_3_bad: "ઉત્પાદન પછી ન્યૂનતમ પરીક્ષણ ક્રિટિકલ ઉત્પાદન પ્રક્રિયાઓમાં લીકેજ અને નિષ્ફળતાનું ઊંચું જોખમ ઊભું કરે છે.",
    cta_row_3_good: "ફરજિયાત હિલિયમ, રેડિયોગ્રાફી, અલ્ટ્રાસોનિક અને હાઇડ્રોસ્ટેટિક ટેસ્ટિંગ ડિલિવરી પહેલાં શૂન્ય ખામીની ખાતરી કરે છે.",
    cta_row_4_bad: "અનમ્ય ડિઝાઇન જે પૂર્વ-અસ્તિત્વમાં રહેલા પ્લાન્ટ લેઆઉટ અને પાઇપિંગ રૂપરેખાંકનોમાં ફિટ કરવી મુશ્કેલ છે.",
    cta_row_4_good: "દરજી દ્વારા બનાવેલા સ્ટ્રક્ચરલ સ્કીડ અને કસ્ટમાઇઝ્ડ પાઇપિંગ લેઆઉટ તમારી ચોક્કસ જગ્યા અને પ્રક્રિયા જરૂરિયાતોને બંધબેસે છે.",
    cta_btn: "એન્જિનિયર સાથે વાત કરો",
    
    // Footer
    footer_headline_1: "એન્જિનિયર સાથે વાત કરો,",
    footer_headline_2: "સેલ્સ ટીમ સાથે નહીં",
    footer_follow: "અમને ફોલો કરો",
    footer_rights: "© 2026 જ્યુપિટર એન્જિનિયરિંગ સોલ્યુશન્સ. સર્વાધિકાર સુરક્ષિત.",
    footer_privacy: "ગોપનીયતા નીતિ",
    footer_imprint: "ઇમ્પ્રિન્ટ",
    footer_cookies: "કૂકીઝ",
    footer_branding: "અલી દ્વારા બ્રાન્ડિંગ",
    footer_design: "ડાયલન દ્વારા ડિઝાઇન",
    footer_tagline: "નવીનતા દ્વારા કાર્યક્ષમતા: તમારી ગરમી, અમારું એક્સચેન્જ",
    footer_address: "ગેટ નં. 20/5, કેવ્ઝ કાઉન્ટી રિસોર્ટ્સ પાસે, મુંબઈ આગ્રા હાઇવે, વિલ્હોળી, નાશિક - 422010",
    footer_email: "jupiterengg18@gmail.com",
    footer_phone: "8600031275 / 9766963331",

    // Sustainability Page
    sust_commitment: "અમારી પ્રતિબદ્ધતા",
    sust_hero_title_1: "એન્જિનિયરિંગ એ",
    sust_hero_title_italic: "હરિયાળું",
    sust_hero_title_2: "ઔદ્યોગિક ભવિષ્ય",
    sust_hero_desc: "જ્યુપિટર એન્જિનિયરિંગ સોલ્યુશન્સ ખાતે, ટકાઉપણું એ ચેકબોક્સ નથી — તે અમે ડિઝાઇન કરીએ છીએ તે દરેક હીટ એક્સચેન્જર, અમે મેળવીએ છીએ તે દરેક મટિરિયલ અને અમે ઓપ્ટિમાઇઝ કરીએ છીએ તે દરેક પ્રક્રિયામાં જડિત છે.",
    sust_hero_btn: "પર્યાવરણ નીતિ જુઓ",
    sust_green_scheme_title: "અમારી ગ્રીન યોજના",
    sust_green_scheme_desc: "જ્યુપિટર એન્જિનિયરિંગ માત્ર વિશ્વ-કક્ષાના હીટ ટ્રાન્સફર સાધનો બનાવતું નથી — અમે દરેક તબક્કે પર્યાવરણ માટે ઊંડા આદર સાથે આ કરીએ છીએ. ટકાઉપણું અમારા DNAમાં છે.",
    sust_green_init_title: "પ્રોત્સાહન",
    sust_green_init_italic: "ગ્રીન",
    sust_green_init_title_2: "પહેલ",
    sust_green_init_desc: "ત્રણ સ્તંભો જે દરેક સુવિધામાં અમારી પર્યાવરણ વ્યૂહરચનાને ચલાવે છે.",
    sust_card_1_title: "થર્મલ વેસ્ટ રિકવરી",
    sust_card_1_desc: "અમારા હીટ એક્સચેન્જર્સ 92% સુધી પ્રક્રિયા કચરાની ગરમી પુનઃ મેળવવા માટે એન્જિનિયર્ડ છે, તેને ઉત્પાદન ચક્રમાં પાછી વાળે છે — ઇંધણ વપરાશ અને CO₂ ઉત્સર્જન નાટ્યાત્મક રીતે ઘટાડે છે.",
    sust_card_2_title: "ઓછા-ઉત્સર્જન મટિરિયલ્સ",
    sust_card_2_desc: "અમે ફક્ત સિન્થેટિક ગ્રેફાઇટ અને કાટ-પ્રતિરોધક એલોયનો ઉપયોગ કરીએ છીએ જે 100% રિસાયકલ કરી શકાય છે. અમારી મેન્યુફેક્ચરિંગ પ્રક્રિયાઓ VOC ઉત્સર્જનને સ્ત્રોત પર જ દૂર કરે છે.",
    sust_card_3_title: "પાણી-સકારાત્મક કામગીરી",
    sust_card_3_desc: "તમામ સુવિધાઓમાં ઝીરો-ડિસ્ચાર્જ જળ શુદ્ધિકરણ પ્લાન્ટ ખાતરી કરે છે કે પ્રક્રિયા પાણીનું દરેક ટીપું સારવાર, રિસાયકલ અને પરત થાય — 2024 થી પાણી-સકારાત્મક સ્થિતિ હાંસલ.",
    sust_learn_more: "વધુ જાણો",
    sust_env_title_1: "પર્યાવરણ",
    sust_env_title_italic: "સુરક્ષા",
    sust_env_title_2: "પહેલ",
    sust_env_1: "ભૂગર્ભ જળ દૂષણ અટકાવતી ક્લોઝ્ડ-લૂપ કૂલન્ટ સિસ્ટમ્સ",
    sust_env_2: "CPCB ધોરણો કરતાં 40% વધુ માસિક સ્ટેક ઉત્સર્જન પરીક્ષણ",
    sust_env_3: "તમામ પ્લાન્ટ્સમાં ISO 14001:2015 પ્રમાણિત પર્યાવરણ વ્યવસ્થાપન",
    sust_env_4: "તમામ ધૂળ બિંદુઓ પર ઇલેક્ટ્રોસ્ટેટિક પ્રિસિપિટેટર્સ અને બેગ ફિલ્ટર્સની સ્થાપના",
    sust_env_5: "NABL-માન્ય એજન્સીઓ દ્વારા દ્વિમાસિક એમ્બિયન્ટ હવા ગુણવત્તા મોનિટરિંગ",
    sust_env_6: "95% રિસાયક્લિંગ દર સાથે ઘન કચરાનું વર્ગીકરણ — 2027 સુધીમાં ઝીરો લેન્ડફિલ લક્ષ્ય",
    sust_env_7: "વાર્ષિક 1.2 કરોડ લિટર કેપ્ચર કરતી વરસાદી પાણી સંગ્રહ ઇન્ફ્રાસ્ટ્રક્ચર",
    sust_env_8: "તમામ થર્મલ પ્રક્રિયાઓમાં ફર્નેસ ઓઇલને નેચરલ ગેસ વડે બદલવું",
    sust_env_9: "સુવિધાઓમાં 15,000+ દેશી વૃક્ષો વાવીને ગ્રીન બેલ્ટ વિકાસ",
    sust_safety_label: "સલામતી પ્રથમ",
    sust_safety_title_1: "જ્યાં ચોકસાઈ",
    sust_safety_title_italic: "સુરક્ષાને",
    sust_safety_1: "તમામ કર્મચારીઓને PPE — હેલ્મેટ, ગરમી-પ્રતિરોધક ગ્લવ્ઝ, સેફ્ટી શૂઝ અને આંખની સુરક્ષા સાથે સજ્જ",
    sust_safety_2: "માસિક સલામતી કવાયત અને ત્રિમાસિક ઇમર્જન્સી ઇવેક્યુએશન સિમ્યુલેશન",
    sust_safety_3: "ગેસ ડિટેક્શન પ્રોટોકોલ સાથે CCTV-મોનિટર્ડ કન્ફાઇન્ડ સ્પેસ એન્ટ્રી",
    sust_safety_4: "પ્રમાણિત એન્જિનિયર્સ દ્વારા સાપ્તાહિક ફાયર એક્સટિંગ્વિશર અને હાઇડ્રન્ટ સિસ્ટમ્સ તપાસ",
    sust_safety_5: "પ્રેશર વેસલ્સ અને સ્ટોરેજ ટેન્ક વાર્ષિક લોડ-બેરિંગ પ્રમાણપત્ર",
    sust_safety_btn: "સલામતી નીતિ જુઓ",
    sust_health_label: "આરોગ્ય",
    sust_health_title_1: "અમે અમારા",
    sust_health_title_italic: "લોકોની",
    sust_health_desc: "અમારા પ્લાન્ટ્સે દરેક કર્મચારીના સ્વાસ્થ્ય અને કલ્યાણની રક્ષા માટે વ્યાપક પહેલ અપનાવી છે. અમારી સુવિધાઓમાં અપનાવવામાં આવેલા કેટલાક મુખ્ય પગલાં.",
    sust_health_1: "તમામ કામદારો માટે ESIC અને પર્સનલ એક્સિડન્ટ કવરેજ",
    sust_health_2: "લાયક ચિકિત્સકો દ્વારા દ્વિવાર્ષિક સ્વાસ્થ્ય તપાસ",
    sust_health_3: "અધિકારીઓ અને કર્મચારીઓ માટે મેડિક્લેમ અને PA પોલિસી",
    sust_health_4: "ધૂળ, ધુમાડો અને ગરમીનો સંપર્ક માન્ય મર્યાદાઓ નીચે નિયંત્રિત",
    sust_cta_title: "ટકાઉ ભવિષ્ય માટે અમારી સાથે ભાગીદારી કરો",
    sust_cta_desc: "અમારા થર્મલી કાર્યક્ષમ, ઓછા-ઉત્સર્જન હીટ એક્સચેન્જર્સ કેવી રીતે તમારા પ્લાન્ટના કાર્બન ફૂટપ્રિન્ટને ઘટાડી શકે છે તે શોધો.",
    sust_cta_btn: "પરામર્શ શેડ્યૂલ કરો",

    // Testimonials content
    test_1_text: "અમે જ્યુપિટરને શેલ અને ટ્યુબ હીટ એક્સચેન્જર્સના કસ્ટમ સેટ માટે કમિશન કર્યું. થર્મલ કાર્યક્ષમતા અમારી સ્પેસિફિકેશન કરતાં 12% વધી ગઈ, જેનાથી અમારા ઉપયોગિતા ખર્ચમાં નોંધપાત્ર ઘટાડો થયો.",
    test_2_name: "ડૉ. રાજેશ મહેતા",
    test_2_title: "ઓપરેશન્સ ડિરેક્ટર, કેમી ઇન્ડિયા",
    test_2_text: "જ્યુપિટરની ડિઝાઇન એન્જિનિયરિંગ ટીમ પાસે ઊંડી ટેકનિકલ નિપુણતા છે. તેમણે બેફલ સ્પેસિંગ ઓપ્ટિમાઇઝ કરવા માટે વ્યાપક HTRI સિમ્યુલેશન ચલાવ્યું, જેણે વર્ષોથી અમારા પ્લાન્ટને પરેશાન કરતી ક્રોનિક ફાઉલિંગ સમસ્યાનું નિરાકરણ કર્યું.",
    test_3_name: "વિક્રમ મલ્હોત્રા",
    test_3_title: "VP પ્રોજેક્ટ્સ, પેટ્રોકેમ રિફાઇનરી",
    test_3_text: "અમારા રિફાઇનરી વિસ્તરણ માટે, અમને સખત ટાઇમલાઇન પર ASME-પ્રમાણિત પ્રેશર વેસલ્સની જરૂર હતી. જ્યુપિટરે સમય પહેલાં, નિર્દોષ વેલ્ડ ગુણવત્તા અને સંપૂર્ણ ડોક્યુમેન્ટેશન સાથે ડિલિવરી કરી.",
    test_4_text: "તેમના ગ્રેફાઇટ હીટ એક્સચેન્જર્સે અમારી આક્રમક એસિડ હીટિંગ સમસ્યાઓનું નિરાકરણ કર્યું. ખરેખર ઉત્કૃષ્ટ કાટ પ્રતિકાર અને ત્વરિત સેવા.",
    test_5_name: "અમિતાભ શાહ",
    test_5_title: "ચીફ એન્જિનિયર, ગુજરાત ક્લોર-આલ્કલી",
    test_5_text: "ટીમ માત્ર ફેબ્રિકેટ જ નથી કરતી; તેઓ મૂલ્યવાન ડિઝાઇન ફીડબેક પ્રદાન કરે છે. ટ્યુબ શીટ મટિરિયલ્સ પરની તેમની ભલામણોએ અમને અકાળ ગેલ્વેનિક કોરોઝનથી બચાવ્યા.",
    test_6_name: "સંજય રેડ્ડી",
    test_6_title: "જનરલ મેનેજર, ડેક્કન પાવર કોર્પ",
    test_6_text: "જ્યુપિટરે ટૂંકા મેન્ટેનન્સ શટડાઉન દરમિયાન અમારા મોટા સ્ટીમ કન્ડેન્સર્સને રિફર્બિશ કરવામાં મદદ કરી. તેમના 24/7 સપોર્ટ અને ચોક્કસ રી-ટ્યુબિંગે અમને સમયસર પાછા ઓનલાઇન લાવ્યા.",
  },
  te: {
    // Navbar
    manifesto: "మేనిఫెస్టో",
    services: "సేవలు",
    cases: "కేసులు",
    about: "మా గురించి",
    resources: "వనరులు",
    blog: "బ్లాగ్",
    growth_assets: "గ్రోత్ అసెట్స్",
    talk_to_us: "మాతో మాట్లాడండి",
    jupiter_title: "జూపిటర్ ఇంజనీరింగ్ సొల్యూషన్స్",
    home: "హోమ్",
    order: "మాతో కనెక్ట్ అవ్వండి",
    products: "ఉత్పత్తులు",
    about_us: "మా గురించి",
    others: "ఇతరములు",
    sustainability: "సుస్థిరత",
    about_hero_title_main: "జూపిటర్ ఇంజనీరింగ్ ",
    about_hero_title_italic: "సొల్యూషన్స్",
    about_hero_sub: "2018లో స్థాపించబడిన మేము, ప్రాసెస్ పరికరాల ఫ్యాబ్రికేషన్, ఇంజనీరింగ్ మరియు తయారీలో అగ్రగామి శక్తి. మూడు దశాబ్దాలకు పైగా సంయుక్త అనుభవంతో, మా బృందం ఫార్మాస్యూటికల్స్, కెమికల్స్, రిఫైనరీలు, పెట్రోకెమికల్స్ మరియు ఆయిల్ & గ్యాస్ పరిశ్రమలకు అత్యాధునిక థర్మల్ సొల్యూషన్లు అందిస్తుంది.",
    about_vision_title: "మా విజన్ & విలువలు",
    about_vision_desc: "గ్రాఫైట్ రంగంలో భవిష్యత్ నాయకులు కావడానికి మేము కట్టుబడి ఉన్నాము. ఖచ్చితత్వం, సమగ్రత మరియు ఆవిష్కరణలు మా ఇంజనీరింగ్ తత్వశాస్త్రానికి మూలస్తంభాలు. ఉత్తమ ఫలితాల కోసం మేము నైపుణ్యంపై ఆధారపడతాము.",
    about_standards_title: "అనుకూలత & డిజైన్ ప్రమాణాలు",
    about_standards_desc: "ASME, TEMA మరియు DIN ప్రమాణాలతో సహా అంతర్జాతీయ నిబంధనలను మేము ఖచ్చితంగా పాటిస్తాము. మా అధునాతన డిజైన్ సామర్థ్యాలలో HTRI 9, ప్రొప్రైటరీ సాఫ్ట్‌వేర్, AspenTech ప్రాసెస్ సిమ్యులేషన్, AutoCAD మరియు SolidWorks ఉన్నాయి.",
    about_value_1: "థర్మల్ ప్రెసిషన్ ఇంజనీరింగ్",
    about_value_2: "మెటీరియల్ మన్నిక & గ్రాఫైట్ నైపుణ్యం",
    about_value_3: "కస్టమర్ లైఫ్‌సైకిల్ భాగస్వామ్యం",
    about_cta_title: "కస్టమ్ బిల్డ్ కావాలా?",
    about_cta_desc: "మీ పారామితుల కోసం ధృవీకరించబడిన HTRI హీట్ ట్రాన్స్‌ఫర్ లెక్కింపు చేయడానికి మా థర్మల్ ఇంజనీరింగ్ నిపుణులను సంప్రదించండి.",
    about_cta_btn: "సంప్రదింపు షెడ్యూల్ చేయండి",
    order_hero_title_main: "మాతో ",
    order_hero_title_italic: "కనెక్ట్ అవ్వండి",
    order_hero_sub: "మీ ప్రక్రియ అవసరాలను చర్చించడానికి, కస్టమ్ హీట్ ఎక్స్ఛేంజర్‌లను డిజైన్ చేయడానికి లేదా సాంకేతిక అంచనాలను అభ్యర్థించడానికి మా ఇంజనీరింగ్ బృందాన్ని సంప్రదించండి.",
    order_form_params: "Process Parameters",
    order_form_hot_in: "Hot Side Inlet Temp (°C)",
    order_form_hot_out: "Hot Side Outlet Temp (°C)",
    order_form_cold_in: "Cold Side Inlet Temp (°C)",
    order_form_cold_out: "Cold Side Outlet Temp (°C)",
    order_form_flow: "Flow Rate (kg/h)",
    order_form_name: "పూర్తి పేరు",
    order_form_email: "ఈమెయిల్ చిరునామా",
    order_form_message: "ప్రాజెక్ట్ అవసరాలు / సందేశం",
    order_form_material: "మెటీరియల్ ఎంపిక",
    order_form_type: "ఎక్స్‌చేంజర్ రకం",
    order_form_submit: "అభ్యర్థనను పంపండి",
    order_form_success: "ధన్యవాదాలు! మా ఇంజనీరింగ్ బృందం త్వరలోనే మిమ్మల్ని సంప్రదిస్తుంది.",
    
    // Hero
    hero_headline_1: "భవిష్యత్ అగ్రగామి",
    hero_headline_2: "అన్ని విషయాలలోనూ",
    hero_headline_3: "గ్రాఫైట్",
    hero_subtext: "కీలకమైన పారిశ్రామిక అనువర్తనాల కోసం ప్రాసెస్ పరికరాల ఫ్యాబ్రికేషన్, ఇంజనీరింగ్ మరియు తయారీ. మూడు దశాబ్దాలకు పైగా సంయుక్త అనుభవంతో, సాధ్యమైనంత ఉత్తమ ఫలితాల కోసం మీ ప్రక్రియలను ఆప్టిమైజ్ చేయడానికి మేము మా నైపుణ్యంపై ఆధారపడతాము.",
    hero_cta: "సాంకేతిక సంప్రదింపుల కోసం అభ్యర్థించండి",
    
    // PainPoints
    painpoints_title: "మీ ప్రక్రియలు ప్రపంచ స్థాయి ప్రమాణాలతో ఉన్నాయి. మీ థర్మల్ పరికరాలు అవరోధం కాకూడదు.",
    problem_1_title: "తుప్పు & పరికరాల విఫలం",
    problem_1_body: "HCl, H₂SO₄ మరియు ఫాస్ఫారిక్ ఆమ్లం వంటి దూకుడు రసాయనాలను నిర్వహిస్తున్నప్పుడు ప్రామాణిక మెటల్ హీట్ ఎక్స్‌చేంజర్లు వేగంగా క్షీణిస్తాయి, ఇది ప్రమాదకరమైన లీకేజీలు మరియు ఖరీదైన ప్లాంట్ షట్‌డౌన్‌లకు కారణమవుతుంది.",
    problem_2_title: "సబ్-ఆప్టిమల్ థర్మల్ డిజైన్ & ఫౌలింగ్",
    problem_2_body: "సాధారణ పరికరాలకు ఖచ్చితమైన HTRI థర్మల్ రేటింగ్‌లు లేవు, దీని వల్ల అధిక ప్రెషర్ డ్రాప్, శక్తి వృథా మరియు హీట్ ట్రాన్స్‌ఫర్ సామర్థ్యాన్ని తగ్గించే తరచుగా ట్యూబ్ ఫౌలింగ్ ఏర్పడుతుంది.",
    problem_3_title: "నాణ్యత & భద్రతా నిబంధనల అంతరాలు",
    problem_3_body: "సబ్‌స్టాండర్డ్ వెల్డింగ్ మరియు కఠినమైన నాన్-డిస్ట్రక్టివ్ టెస్టింగ్ (అల్ట్రాసోనిక్, రేడియోగ్రఫీ, డై పెనిట్రేషన్, హీలియం) లేకపోవడం వల్ల కీలక ప్రాసెస్ జోన్‌లలో విఫలత ప్రమాదాలు పెరుగుతాయి.",
    problem_4_title: "అసమర్ధమైన ఉత్పత్తి సామర్థ్యం & ఆలస్యాలు",
    problem_4_body: "అధునాతన యంత్రాలు, 35-అడుగుల EOT క్రేన్‌లు మరియు 6,000 చ.అ. వర్క్‌షాప్‌లు లేని తయారీదారులు పెద్ద స్ట్రక్చరల్ స్కిడ్‌లను నిర్వహించలేరు లేదా సమయానికి పూర్తి చేయలేరు.",
    problem_5_title: "నమ్మదగిన నిర్వహణ & రీ-ట్యూబింగ్ లేకపోవడం",
    problem_5_body: "ఇన్‌స్టాలేషన్ తర్వాత, సమయానికి ఆన్-సైట్ శుభ్రపరచడం, హీట్ ఎక్స్‌చేంజర్ మరమ్మత్తు మరియు విడిభాగాల మార్పిడి సేవలు కనుగొనడం కష్టం, ఇది ఎక్కువ కాలం ప్లాంట్ నిలిపివేతకు కారణమవుతుంది.",
    painpoints_cta_title: "మీ హీట్ ట్రాన్స్‌ఫర్ ప్రక్రియలను ఆప్టిమైజ్ చేయడానికి సిద్ధంగా ఉన్నారా? మీ అవసరాలను చర్చిద్దాం.",
    painpoints_cta_btn: "సాంకేతిక సంప్రదింపు అభ్యర్థించండి",
    
    // Cases
    cases_title_1: "30+ పారిశ్రామిక ప్లాంట్లతో నిరూపితమైంది,",
    cases_title_2: "వారు తమ హీట్ ట్రాన్స్‌ఫర్‌ను ఆప్టిమైజ్ చేయడం కోసం",
    cases_title_3: "మమ్మల్ని నమ్మారు",
    cases_explore_btn: "మా కేసులు అన్వేషించండి",
    cases_explore_hover: "కేసు చూడండి",
    cases_coming_soon: "త్వరలో రాబోతోంది",
    
    // Services (Heat Exchangers)
    services_1_heading: "షెల్ & ట్యూబ్ ఎక్స్‌చేంజర్స్",
    services_1_body: "అధిక పీడనం మరియు అధిక ఉష్ణోగ్రత ప్రక్రియల కోసం రూపొందించబడింది. ఫార్మా, కెమికల్ మరియు పెట్రోకెమికల్ ప్లాంట్లలో కఠినమైన పారిశ్రామిక పరిస్థితులలో ఉత్తమ థర్మల్ పనితీరు మరియు గరిష్ట మన్నికను అందించే షెల్ మరియు ట్యూబ్ ఎక్స్‌చేంజర్‌లను మేము డిజైన్ చేస్తాము.",
    services_2_heading: "గ్రాఫైట్ టెక్నాలజీ",
    services_2_body: "తీవ్రమైన రసాయన ప్రక్రియల కోసం ఎదురులేని తుప్పు నిరోధకత. మా గ్రాఫైట్ పాలీబ్లాక్ హీట్ ఎక్స్‌చేంజర్లు అసాధారణమైన థర్మల్ వాహకతను అందిస్తాయి, HCl, H₂SO₄ మరియు ఫాస్ఫారిక్ ఆమ్లం వంటి అత్యంత తుప్పు పట్టించే ద్రావణాలను నిర్వహించడానికి అనువుగా ఉంటాయి.",
    services_3_heading: "ఖచ్చితమైన థర్మల్ డిజైన్",
    services_3_body: "అధునాతన HTRI 9 లెక్కలు, ప్రొప్రైటరీ సాఫ్ట్‌వేర్ మరియు AspenTech ప్రాసెస్ సిమ్యులేషన్‌లను ఉపయోగించి ఆప్టిమైజ్ చేయబడిన ఉష్ణ బదిలీ. పీడన డ్రాప్‌ను తగ్గించడానికి మరియు ట్యూబ్‌లలో వ్యర్థాలు చేరకుండా ఉండటానికి మేము ట్యూబ్ లేఅవుట్‌లు మరియు బాఫిల్ స్పేసింగ్‌ను అనుకూలీకరిస్తాము.",
    services_4_heading: "లైఫ్‌సైకిల్ పెర్ఫార్మెన్స్",
    services_4_body: "35-అడుగుల EOT క్రేన్‌తో మా 6,000 చ.అ. వర్క్‌షాప్ ద్వారా మద్దతునిచ్చే పూర్తి నిర్వహణ, పునరుద్ధరణ మరియు రీ-ట్యూబింగ్ సేవలు. మీ హీట్ ట్రాన్స్‌ఫర్ సిస్టమ్‌లు గరిష్ట పనితీరుతో నిరంతరం పనిచేయడాన్ని మేము నిర్ధారిస్తాము.",
    services_discover_btn: "మా పరిష్కారాలను కనుగొనండి",
    
    // Testimonials
    testimonials_title_1: "మేము థర్మల్ మరియు ప్రాసెస్",
    testimonials_title_2: "వ్యవస్థలను మన్నికగా డిజైన్ చేస్తాము",
    testimonials_subtext: "థర్మల్ డిజైన్ నుండి కస్టమ్ ఫ్యాబ్రికేషన్ వరకు, ఫార్మాస్యూటికల్స్, కెమికల్స్ మరియు రిఫైనరీలలో గరిష్ట కార్యాచరణ విశ్వసనీయత కోసం రూపొందించబడిన హీట్ ఎక్స్‌చేంజర్లు మరియు ప్రెజర్ వెసెల్స్ అందిస్తాము.",
    
    // CTA Section
    cta_title_1: "కేటలాగ్ పరికరాల కంటే",
    cta_title_2: "ఇంజనీర్డ్ విశ్వసనీయతను ఎంచుకోండి",
    cta_subtext: "సాధారణ ప్రాసెస్ పరికరాలు థర్మల్ సామర్థ్యం మరియు రసాయన భద్రతలో రాజీ పడతాయి. HTRI ఖచ్చితత్వంతో డిజైన్ చేసి మన్నికగా నిర్మించిన కస్టమ్-ఇంజనీర్డ్ థర్మల్ పరిష్కారాలతో మీ సిస్టమ్‌ను ఆప్టిమైజ్ చేయండి.",
    cta_table_isolated_title: "కేటలాగ్ పరికరాలు",
    cta_table_isolated_sub: "ప్రామాణిక డిజైన్‌లు & సాధారణ ప్రాసెస్ వెసెల్స్",
    cta_table_wgb_title: "జూపిటర్ ఇంజనీర్డ్ సిస్టమ్స్",
    cta_table_wgb_sub: "గరిష్ట విశ్వసనీయత కోసం కస్టమ్-డిజైన్ చేసిన ప్రాసెస్ పరికరాలు",
    cta_row_1_bad: "ప్రామాణిక మెటల్ ఎక్స్‌చేంజర్లు కఠినమైన రసాయనాల వల్ల వేగంగా తుప్పు పడతాయి, ప్రమాదకరమైన లీకేజీలు మరియు షట్‌డౌన్‌లకు కారణమవుతాయి.",
    cta_row_1_good: "కస్టమ్ గ్రాఫైట్ పాలీబ్లాక్‌లు మరియు ప్రీమియం అల్లాయ్‌లు దూకుడు ఆమ్ల వాతావరణాలకు ఎదురులేని తుప్పు నిరోధకతను నిర్ధారిస్తాయి.",
    cta_row_2_bad: "ప్రామాణిక కాన్ఫిగరేషన్‌లు సాధారణ ట్యూబ్ లేఅవుట్‌ల వల్ల అధిక ప్రెషర్ డ్రాప్ మరియు తక్కువ థర్మల్ సామర్థ్యంతో బాధపడతాయి.",
    cta_row_2_good: "HTRI 9, ప్రొప్రైటరీ సాఫ్ట్‌వేర్ మరియు AspenTech సిమ్యులేషన్‌లు ఖచ్చితంగా ఆప్టిమైజ్ చేసిన డిజైన్‌లతో హీట్ ట్రాన్స్‌ఫర్‌ను గరిష్టం చేస్తాయి.",
    cta_row_3_bad: "తయారీ తర్వాత కనీస పరీక్ష కీలక ఉత్పత్తి ప్రక్రియలలో లీకేజీ మరియు విఫలత ప్రమాదాన్ని పెంచుతుంది.",
    cta_row_3_good: "తప్పనిసరి హీలియం, రేడియోగ్రఫీ, అల్ట్రాసోనిక్ మరియు హైడ్రోస్టాటిక్ టెస్టింగ్ డెలివరీకి ముందు సున్నా లోపాలను ధృవీకరిస్తుంది.",
    cta_row_4_bad: "ముందుగా ఉన్న ప్లాంట్ లేఅవుట్‌లు మరియు పైపింగ్ కాన్ఫిగరేషన్‌లలో అమర్చడం కష్టమైన మారని డిజైన్‌లు.",
    cta_row_4_good: "అనుకూల స్ట్రక్చరల్ స్కిడ్‌లు మరియు కస్టమైజ్డ్ పైపింగ్ లేఅవుట్‌లు మీ ఖచ్చితమైన స్థలం మరియు ప్రాసెస్ అవసరాలకు సరిపోతాయి.",
    cta_btn: "ఇంజనీర్‌తో మాట్లాడండి",
    
    // Footer
    footer_headline_1: "ఇంజనీర్‌తో మాట్లాడండి,",
    footer_headline_2: "సేల్స్ టీమ్‌తో కాదు",
    footer_follow: "మమ్మల్ని ఫాలో అవ్వండి",
    footer_rights: "© 2026 జూపిటర్ ఇంజనీరింగ్ సొల్యూషన్స్. సర్వ హక్కులు ప్రత్యేకించబడినవి.",
    footer_privacy: "గోప్యతా విధానం",
    footer_imprint: "ఇంప్రింట్",
    footer_cookies: "కుకీలు",
    footer_branding: "అలీ బ్రాండింగ్",
    footer_design: "డైలాన్ డిజైన్",
    footer_tagline: "ఆవిష్కరణ ద్వారా సామర్థ్యం: మీ వేడి, మా ఎక్స్‌చేంజ్",
    footer_address: "గేట్ నం. 20/5, కేవ్స్ కౌంటీ రిసార్ట్స్ పక్కన, ముంబై ఆగ్రా హైవే, విల్హోళీ, నాశిక్ - 422010",
    footer_email: "jupiterengg18@gmail.com",
    footer_phone: "8600031275 / 9766963331",

    // Sustainability Page
    sust_commitment: "మా నిబద్ధత",
    sust_hero_title_1: "ఇంజనీరింగ్ ఏ",
    sust_hero_title_italic: "పచ్చని",
    sust_hero_title_2: "పారిశ్రామిక భవిష్యత్తు",
    sust_hero_desc: "జూపిటర్ ఇంజనీరింగ్ సొల్యూషన్స్ వద్ద, సుస్థిరత అనేది చెక్‌బాక్స్ కాదు — మేము డిజైన్ చేసే ప్రతి హీట్ ఎక్స్‌చేంజర్, మేము సేకరించే ప్రతి మెటీరియల్ మరియు మేము ఆప్టిమైజ్ చేసే ప్రతి ప్రక్రియలో ఇది భాగం.",
    sust_hero_btn: "పర్యావరణ విధానం చూడండి",
    sust_green_scheme_title: "మా గ్రీన్ స్కీమ్",
    sust_green_scheme_desc: "జూపిటర్ ఇంజనీరింగ్ ప్రపంచ స్థాయి హీట్ ట్రాన్స్‌ఫర్ పరికరాలను తయారు చేయడం మాత్రమే కాదు — ప్రతి దశలో పర్యావరణం పట్ల లోతైన గౌరవంతో చేస్తాము. సుస్థిరత మా DNAలో భాగం.",
    sust_green_init_title: "ప్రోత్సహించడం",
    sust_green_init_italic: "గ్రీన్",
    sust_green_init_title_2: "చొరవలు",
    sust_green_init_desc: "ప్రతి సదుపాయంలో మా పర్యావరణ వ్యూహాన్ని నడిపించే మూడు స్తంభాలు.",
    sust_card_1_title: "థర్మల్ వేస్ట్ రికవరీ",
    sust_card_1_desc: "మా హీట్ ఎక్స్‌చేంజర్లు 92% వరకు ప్రక్రియ వ్యర్థ ఉష్ణాన్ని తిరిగి పొందేలా రూపొందించబడ్డాయి, దాన్ని ఉత్పత్తి చక్రాలలోకి మళ్లిస్తాయి — ఇంధన వినియోగం మరియు CO₂ ఉద్గారాలను నాటకీయంగా తగ్గిస్తాయి.",
    sust_card_2_title: "తక్కువ-ఉద్గార మెటీరియల్స్",
    sust_card_2_desc: "మేము 100% రీసైకిల్ చేయగల సింథటిక్ గ్రాఫైట్ మరియు తుప్పు-నిరోధక అల్లాయ్‌లను మాత్రమే ఉపయోగిస్తాము. మా తయారీ ప్రక్రియలు VOC ఉద్గారాలను మూలం వద్దనే తొలగిస్తాయి.",
    sust_card_3_title: "నీరు-సానుకూల కార్యకలాపాలు",
    sust_card_3_desc: "అన్ని సదుపాయాలలో జీరో-డిశ్చార్జ్ నీటి శుద్ధి ప్లాంట్లు ప్రతి ప్రాసెస్ నీటి చుక్కను శుద్ధి చేసి, రీసైకిల్ చేసి, తిరిగి ఇస్తాయి — 2024 నుండి నీటి-సానుకూల స్థితి సాధించాము.",
    sust_learn_more: "మరింత తెలుసుకోండి",
    sust_env_title_1: "పర్యావరణ",
    sust_env_title_italic: "రక్షణ",
    sust_env_title_2: "చొరవలు",
    sust_env_1: "భూగర్భ జలాల కాలుష్యాన్ని నిరోధించే క్లోజ్డ్-లూప్ కూలంట్ సిస్టమ్‌లు",
    sust_env_2: "CPCB నిబంధనలను 40% మించిన నెలవారీ స్టాక్ ఉద్గార పరీక్ష",
    sust_env_3: "అన్ని ప్లాంట్లలో ISO 14001:2015 ధృవీకరించబడిన పర్యావరణ నిర్వహణ",
    sust_env_4: "అన్ని ధూళి బిందువుల వద్ద ఎలక్ట్రోస్టాటిక్ ప్రిసిపిటేటర్లు మరియు బ్యాగ్ ఫిల్టర్ల అమరిక",
    sust_env_5: "NABL-గుర్తింపు పొందిన ఏజెన్సీల ద్వారా ద్విమాస పరిసర గాలి నాణ్యత పర్యవేక్షణ",
    sust_env_6: "95% రీసైక్లింగ్ రేటుతో ఘన వ్యర్థాల వేరుచేయడం — 2027 నాటికి జీరో ల్యాండ్‌ఫిల్ లక్ష్యం",
    sust_env_7: "ఏటా 1.2 కోట్ల లీటర్లు సేకరించే వర్షపు నీటి సంగ్రహ మౌలిక సదుపాయం",
    sust_env_8: "అన్ని థర్మల్ ప్రక్రియలలో ఫర్నేస్ ఆయిల్‌ను సహజ వాయువుతో భర్తీ చేయడం",
    sust_env_9: "సదుపాయాల్లో 15,000+ స్థానిక చెట్లు నాటి గ్రీన్ బెల్ట్ అభివృద్ధి",
    sust_safety_label: "భద్రత ముందు",
    sust_safety_title_1: "ఖచ్చితత్వం కలిసే చోట",
    sust_safety_title_italic: "రక్షణ",
    sust_safety_1: "అన్ని సిబ్బందికి PPE — హెల్మెట్లు, వేడి-నిరోధక గ్లవ్స్, భద్రతా బూట్లు మరియు కన్ను రక్షణతో సజ్జీకరించబడ్డారు",
    sust_safety_2: "నెలవారీ భద్రతా విన్యాసాలు మరియు త్రైమాసిక అత్యవసర ఖాళీ చేయడం సిమ్యులేషన్‌లు",
    sust_safety_3: "గ్యాస్ డిటెక్షన్ ప్రోటోకాల్స్‌తో CCTV-పర్యవేక్షించబడిన పరిమిత ప్రదేశ ప్రవేశం",
    sust_safety_4: "ధృవీకరించబడిన ఇంజనీర్ల ద్వారా వారపు అగ్నిమాపక యంత్రాలు మరియు హైడ్రంట్ సిస్టమ్‌ల తనిఖీ",
    sust_safety_5: "ప్రెజర్ వెసెల్స్ మరియు స్టోరేజ్ ట్యాంక్‌లు వార్షిక లోడ్-బేరింగ్ ధృవీకరణ",
    sust_safety_btn: "భద్రతా విధానం చూడండి",
    sust_health_label: "ఆరోగ్యం",
    sust_health_title_1: "మేము మా",
    sust_health_title_italic: "వ్యక్తుల",
    sust_health_desc: "ప్రతి ఉద్యోగి ఆరోగ్యం మరియు శ్రేయస్సును కాపాడటానికి మా ప్లాంట్లు విస్తృతమైన చొరవలను అమలు చేశాయి. మా సదుపాయాల్లో అమలు చేసిన కొన్ని ముఖ్యమైన చర్యలు.",
    sust_health_1: "అన్ని కార్మికులకు ESIC & వ్యక్తిగత ప్రమాద బీమా",
    sust_health_2: "అర్హత కలిగిన వైద్యుల ద్వారా ద్వివార్షిక ఆరోగ్య పరీక్షలు",
    sust_health_3: "అధికారులు మరియు సిబ్బందికి మెడిక్లెయిమ్ & PA పాలసీ",
    sust_health_4: "ధూళి, పొగలు & వేడి ఎక్స్‌పోజర్ అనుమతించదగిన పరిమితుల కంటే తక్కువగా నియంత్రించబడుతుంది",
    sust_cta_title: "సుస్థిర భవిష్యత్తు కోసం మాతో భాగస్వామ్యం అవ్వండి",
    sust_cta_desc: "మా థర్మల్‌గా సమర్థమైన, తక్కువ-ఉద్గార హీట్ ఎక్స్‌చేంజర్లు మీ ప్లాంట్ కార్బన్ ఫుట్‌ప్రింట్‌ను ఎలా తగ్గించగలవో అన్వేషించండి.",
    sust_cta_btn: "సంప్రదింపు షెడ్యూల్ చేయండి",

    // Testimonials content
    test_1_text: "మేము జూపిటర్‌ను షెల్ & ట్యూబ్ హీట్ ఎక్స్‌చేంజర్ల కస్టమ్ సెట్ కోసం కమీషన్ చేసాము. థర్మల్ సామర్థ్యం మా స్పెసిఫికేషన్ కంటే 12% మించింది, మా యుటిలిటీ ఖర్చులు గణనీయంగా తగ్గాయి.",
    test_2_name: "డా. రాజేష్ మెహతా",
    test_2_title: "ఆపరేషన్స్ డైరెక్టర్, కెమీ ఇండియా",
    test_2_text: "జూపిటర్ డిజైన్ ఇంజనీరింగ్ టీమ్‌కు లోతైన సాంకేతిక నైపుణ్యం ఉంది. బాఫిల్ స్పేసింగ్‌ను ఆప్టిమైజ్ చేయడానికి వారు సమగ్ర HTRI సిమ్యులేషన్‌లు నిర్వహించారు, సంవత్సరాలుగా మా ప్లాంట్‌ను బాధిస్తున్న దీర్ఘకాలిక ఫౌలింగ్ సమస్యను పరిష్కరించారు.",
    test_3_name: "విక్రమ్ మల్హోత్రా",
    test_3_title: "VP ప్రాజెక్ట్స్, పెట్రోకెమ్ రిఫైనరీ",
    test_3_text: "మా రిఫైనరీ విస్తరణ కోసం, కఠినమైన టైమ్‌లైన్‌లో ASME-ధృవీకరించబడిన ప్రెజర్ వెసెల్స్ అవసరం. జూపిటర్ షెడ్యూల్ కంటే ముందే, లోపరహిత వెల్డ్ నాణ్యత మరియు పూర్తి డాక్యుమెంటేషన్‌తో డెలివరీ చేసింది.",
    test_4_text: "వారి గ్రాఫైట్ హీట్ ఎక్స్‌చేంజర్లు మా దూకుడు ఆమ్ల తాపన సమస్యలను పరిష్కరించాయి. నిజంగా అద్భుతమైన తుప్పు నిరోధకత మరియు తక్షణ సేవ.",
    test_5_name: "అమితాబ్ షా",
    test_5_title: "చీఫ్ ఇంజనీర్, గుజరాత్ క్లోర్-ఆల్కలీ",
    test_5_text: "బృందం కేవలం ఫ్యాబ్రికేట్ చేయడం మాత్రమే కాదు; వారు విలువైన డిజైన్ ఫీడ్‌బ్యాక్ అందిస్తారు. ట్యూబ్ షీట్ మెటీరియల్స్‌పై వారి సిఫార్సులు అకాల గాల్వానిక్ తుప్పు నుండి మమ్మల్ని కాపాడాయి.",
    test_6_name: "సంజయ్ రెడ్డి",
    test_6_title: "జనరల్ మేనేజర్, డెక్కన్ పవర్ కార్ప్",
    test_6_text: "తక్కువ నిర్వహణ షట్‌డౌన్ సమయంలో మా పెద్ద స్టీమ్ కండెన్సర్‌లను పునర్నిర్మించడంలో జూపిటర్ సహాయపడింది. వారి 24/7 మద్దతు మరియు ఖచ్చితమైన రీ-ట్యూబింగ్ మమ్మల్ని సమయానికి తిరిగి ఆన్‌లైన్‌లోకి తీసుకువచ్చింది.",
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations["en"]) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("site_lang");
    return (saved === "en" || saved === "gu" || saved === "te") ? saved : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("site_lang", lang);
  };

  const t = (key: keyof typeof translations["en"]): string => {
    const langTranslations = translations[language] || translations["en"];
    return langTranslations[key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
